#' @title Transform a list of images, class imList, or single im image to a multi or single band SpatRaster object
#' @description
#' This function takes two arguments, the list of covariates as imList generated by imFromStack, 
#' or a single im object, and the target.crs in the style required by the package terra, 
#' for the resulting SpatRaster.
#' @param imList A list of raster im objecs, either created with spatstat or imFromStack.
#' @param target.crs A character string indicating the coordinate reference system for the SpatRaster to return.
#' @return A terra package SpatRaster object with as many bands as items in the imList object.
#' 

as.SpatRast <- function(imList = NULL, 
                        target.crs = NULL){
  
  if(class(imList) != "imList" | class(imList) != "im"){
    stop("Please provide an imList or im object")
  }

  if(class(imList) == "imList"){
    r <- terra::rast(imList[[1]])
    for(i in 2:length(imList)){
      r <- c(r, imlist[[i]])
    }
    
    crs(r) <- target.crs
    return(r)
  }

  if(class(imList) == "im"){
    r <- terra::rast(imList)
    crs(r) <- target.crs
    return(r)
  }
}