#' @title Transform a list of images, class imList, or single im image to a multi or single band SpatRaster object
#' @description
#' This function takes two arguments, the list of covariates as imList generated by imFromStack, 
#' or a single im object, and the target.crs in the style required by the package terra, 
#' for the resulting SpatRaster.
#' @param x A list of raster im objecs, either created with spatstat or imFromStack.
#' @param target.crs A character string indicating the coordinate reference system for the SpatRaster to return.
#' @return A terra package SpatRaster object with as many bands as items in the imList object.
#' @examples
#' \dontrun{
#' iml <- readRDS("inst/extdata/ChelsaBio_imList.rds")
#' 
#' r <- as.SpatRast(x = iml,
#'                  target.crs = "EPSG:6372")
#' }
#' 

as.SpatRast <- function(x = NULL, 
                        target.crs = NULL){
  
  if(!class(x) %in% c("imList" , "im")){
    stop("Please provide an imList or im object")
  }

  if(class(x) == "imList"){
    r <- terra::rast(x[[1]])
    for(i in 2:length(x)){
      r <- c(r, x[[i]])
    }
    
    crs(r) <- target.crs
    return(r)
  }

  if(class(x) == "im"){
    r <- terra::rast(x)
    crs(r) <- target.crs
    return(r)
  }
}